apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.alertmanager.serviceAccountName }}
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.alertmanager.snsRoleArn }}
