environment: dev
image:
  repository: 101533649281.dkr.ecr.us-east-1.amazonaws.com/incode-frontend
  tag: 7f6ede0
replicaCount: 1
service:
  port: 8080
ingress:
  host: dev-devopsblogs.crashbackloop.org
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
