apiVersion: apps/v1
kind: Deployment
metadata:
  name: incode-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: incode-frontend
  template:
    metadata:
      labels:
        app: incode-frontend
    spec:
      containers:
        - name: incode-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
