apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: incode-frontend
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: incode-frontend
          port: {{ .Values.service.port }}
