environment: dev
image:
  repository: 101533649281.dkr.ecr.us-east-1.amazonaws.com/incode-backend
  tag: 5b11d71
replicaCount: 1
service:
  port: 8000
env:
  allowedHosts: "*"
  databaseSecret:
    name: incode-backend-db
    key: DATABASE_URL
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
